services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ppt_game
    container_name: ppt_game
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_DATABASE=ppt_game
      - DB_USERNAME=alvaro
      - DB_PASSWORD=taroba

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ppt_game
      - POSTGRES_USER=alvaro
      - POSTGRES_PASSWORD=taroba
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: